
---

  - name: CONFIGURING INTERFACES
    hosts: ios
    connection: ansible.netcommon.network_cli
    gather_facts: no

    tasks:

       - name: BACKUP CONFIG
         cisco.ios.ios_config:
           backup: True

       - name: CONFIGURING LOOPBACK
         cisco.ios.ios_config:
           parents:
             - interface Loopback200
           commands:
             - ip address 10.200.100.{{ inventory_hostname[-1] }} 255.255.255.255