

---

  - name: AUTO GENERATE FILES AND DIRECTORIES
    hosts: all
    connection: local
    gather_facts: no

    tasks:

      - name: DELETE DIRECTORIES PREVIOUSLY CREATED BASED ON OS
        ansible.builtin.file:
          path: ./tmp
          state: absent
            
          
          