---

  - name: PING TEST AND TRACEROUTE
    hosts: ios
    connection: ansible.netcommon.network_cli
    gather_facts: no

    vars:
      dest: "10.0.0.15"

    tasks:

    - name: ISSUE PING
      cisco.ios.ios_command:
        commands: "ping {{ dest }} repeat 2"
      register: output

    - name: PARSE PING RESPONSE TO OBTAIN % OF SUCCESS
      ansible.builtin.set_fact:
        ping_pct: "{{ output.stdout.0 | regex_search('Success rate is (\\d+)\\s+percent') | regex_search('(\\d+)') }}"

    - ansible.builtin.debug:
        var: ping_pct

    
    # - name: ALTERNATE OPTION FOR PARSING WITH REGEX
    #   ansible.builtin.set_fact:
    #     ping_data2: "{{ output.stdout.0 | regex_findall('Success rate is (\\d+)\\s+percent') | first }}"

    - name: ALTERNATE OPTION FOR PARSING WITH REGEX
      ansible.builtin.set_fact:
        ping_data2: "{{ output.stdout.0 | regex_findall('Success rate is (\\d+)\\s+percent') }}"

    - name: ALTERNATE DEBUG
      ansible.builtin.debug:
        var: ping_data2

    - name: ISSUE TRACEROUTE
      cisco.ios.ios_command:
        commands: "traceroute {{ dest }} timeout 1 ttl 1 5"
      register: traceroute
      when: ping_pct|int < 81

    - name: DEBUG TRACEROUTE
      ansible.builtin.debug:
        var: traceroute

